runtime: nodejs12
service: default
handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  HOST: "0.0.0.0"
  MODE: "PRODUCTION"
